const clients = [{
        "address": "",
        "city": "ירוחם",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אורגד",
        "id": 5315,
        "lastName": "משי",
        "paymentTerms": 0,
        "phone1": "000-3380493",
        "phone2": "000-3442678",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "יוכבד",
        "id": 5314,
        "lastName": "אליאב",
        "paymentTerms": 0,
        "phone1": "000-5659233",
        "phone2": "000-9554206",
        "type": "private"
    },
    {
        "address": "",
        "city": "צפת",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אשר",
        "id": 5313,
        "lastName": "אבהו",
        "paymentTerms": 0,
        "phone1": "000-5928342",
        "phone2": "000-6389657",
        "type": "private"
    },
    {
        "address": "",
        "city": "תל אביב",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "רפאל",
        "id": 5312,
        "lastName": "ברוריה",
        "paymentTerms": 0,
        "phone1": "000-6684161",
        "phone2": "000-6738787",
        "type": "private"
    },
    {
        "address": "",
        "city": "ראש העין",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "עדיאל",
        "id": 5311,
        "lastName": "אתי",
        "paymentTerms": 0,
        "phone1": "000-8048966",
        "phone2": "000-4843652",
        "type": "private"
    },
    {
        "address": "",
        "city": "רמת גן",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "ארי",
        "id": 5310,
        "lastName": "יהב",
        "paymentTerms": 0,
        "phone1": "000-8034396",
        "phone2": "000-1105251",
        "type": "private"
    },
    {
        "address": "",
        "city": "באר שבע",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "איילה",
        "id": 5309,
        "lastName": "אביטוב",
        "paymentTerms": 0,
        "phone1": "000-5284864",
        "phone2": "000-8666012",
        "type": "private"
    },
    {
        "address": "",
        "city": "פתח תקווה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "יהלי",
        "id": 5308,
        "lastName": "הושעיה",
        "paymentTerms": 0,
        "phone1": "000-7479994",
        "phone2": "000-1319216",
        "type": "private"
    },
    {
        "address": "",
        "city": "פתח תקווה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "נתנאל",
        "id": 5307,
        "lastName": "יודפת",
        "paymentTerms": 0,
        "phone1": "000-2968136",
        "phone2": "000-1233487",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירוחם",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "רותם",
        "id": 5306,
        "lastName": "חנוך",
        "paymentTerms": 0,
        "phone1": "000-5424522",
        "phone2": "000-8888611",
        "type": "private"
    },
    {
        "address": "",
        "city": "תל אביב",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אביאור",
        "id": 5305,
        "lastName": "יגְאַל",
        "paymentTerms": 0,
        "phone1": "000-8691013",
        "phone2": "000-8823803",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירוחם",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "ידידיה",
        "id": 5304,
        "lastName": "דגניה",
        "paymentTerms": 0,
        "phone1": "000-2977232",
        "phone2": "000-6371158",
        "type": "private"
    },
    {
        "address": "",
        "city": "צפת",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "גביר",
        "id": 5303,
        "lastName": "גתית",
        "paymentTerms": 0,
        "phone1": "000-2649420",
        "phone2": "000-8240389",
        "type": "private"
    },
    {
        "address": "",
        "city": "ראש העין",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "נווה",
        "id": 5302,
        "lastName": "רפאל",
        "paymentTerms": 0,
        "phone1": "000-8604103",
        "phone2": "000-1351880",
        "type": "private"
    },
    {
        "address": "",
        "city": "ראש העין",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "גואל",
        "id": 5301,
        "lastName": "יוחנן",
        "paymentTerms": 0,
        "phone1": "000-5580407",
        "phone2": "000-7024746",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירוחם",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "יהונדב",
        "id": 5300,
        "lastName": "דניאל",
        "paymentTerms": 0,
        "phone1": "000-1157392",
        "phone2": "000-1186903",
        "type": "private"
    },
    {
        "address": "",
        "city": "פתח תקווה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אילן",
        "id": 5299,
        "lastName": "ליאור",
        "paymentTerms": 0,
        "phone1": "000-3868955",
        "phone2": "000-4749145",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירושלים",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "פנינה",
        "id": 5298,
        "lastName": "כרמלה",
        "paymentTerms": 0,
        "phone1": "000-8525174",
        "phone2": "000-9310438",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "ניסן",
        "id": 5297,
        "lastName": "טובה",
        "paymentTerms": 0,
        "phone1": "000-7597684",
        "phone2": "000-8479848",
        "type": "private"
    },
    {
        "address": "",
        "city": "פתח תקווה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "דורה",
        "id": 5296,
        "lastName": "אצל",
        "paymentTerms": 0,
        "phone1": "000-4821889",
        "phone2": "000-4618384",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירושלים",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "נפתלי",
        "id": 5295,
        "lastName": "גרשון",
        "paymentTerms": 0,
        "phone1": "000-7646189",
        "phone2": "000-6916510",
        "type": "private"
    },
    {
        "address": "",
        "city": "חיפה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אחיה",
        "id": 5294,
        "lastName": "אור-חן",
        "paymentTerms": 0,
        "phone1": "000-4609833",
        "phone2": "000-9844176",
        "type": "private"
    },
    {
        "address": "",
        "city": "רמת גן",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אמוץ",
        "id": 5293,
        "lastName": "עודד",
        "paymentTerms": 0,
        "phone1": "000-8217252",
        "phone2": "000-9858292",
        "type": "private"
    },
    {
        "address": "",
        "city": "תל אביב",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אבנר",
        "id": 5292,
        "lastName": "יערה",
        "paymentTerms": 0,
        "phone1": "000-9184557",
        "phone2": "000-8965475",
        "type": "private"
    },
    {
        "address": "",
        "city": "ראש העין",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אלאור",
        "id": 5291,
        "lastName": "איל",
        "paymentTerms": 0,
        "phone1": "000-9663869",
        "phone2": "000-2699402",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "הְלֵּל",
        "id": 5290,
        "lastName": "לבָנָה",
        "paymentTerms": 0,
        "phone1": "000-2058079",
        "phone2": "000-6121679",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "שאנן",
        "id": 5289,
        "lastName": "לביאה",
        "paymentTerms": 0,
        "phone1": "000-9696454",
        "phone2": "000-8349623",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירוחם",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "עודד",
        "id": 5288,
        "lastName": "מרים",
        "paymentTerms": 0,
        "phone1": "000-5229309",
        "phone2": "000-6333750",
        "type": "private"
    },
    {
        "address": "",
        "city": "פתח תקווה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אליה",
        "id": 5287,
        "lastName": "יהונתן",
        "paymentTerms": 0,
        "phone1": "000-9142728",
        "phone2": "000-1076598",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירוחם",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "תום",
        "id": 5286,
        "lastName": "אלי",
        "paymentTerms": 0,
        "phone1": "000-4177526",
        "phone2": "000-5841400",
        "type": "private"
    },
    {
        "address": "",
        "city": "ראש העין",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "מוריה",
        "id": 5285,
        "lastName": "שהם",
        "paymentTerms": 0,
        "phone1": "000-9546134",
        "phone2": "000-7446779",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אבירן",
        "id": 5284,
        "lastName": "אחווה",
        "paymentTerms": 0,
        "phone1": "000-3742385",
        "phone2": "000-9036142",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירוחם",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "לב",
        "id": 5283,
        "lastName": "אבהו",
        "paymentTerms": 0,
        "phone1": "000-8540639",
        "phone2": "000-9356250",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "חֶמְדָּה",
        "id": 5282,
        "lastName": "אחיה",
        "paymentTerms": 0,
        "phone1": "000-5022954",
        "phone2": "000-7297600",
        "type": "private"
    },
    {
        "address": "",
        "city": "חיפה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אביגיל",
        "id": 5281,
        "lastName": "אבי",
        "paymentTerms": 0,
        "phone1": "000-2836229",
        "phone2": "000-7963572",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירוחם",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "לביאה",
        "id": 5280,
        "lastName": "אלי",
        "paymentTerms": 0,
        "phone1": "000-4053222",
        "phone2": "000-8135373",
        "type": "private"
    },
    {
        "address": "",
        "city": "ראש העין",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אלרום",
        "id": 5279,
        "lastName": "אליסף",
        "paymentTerms": 0,
        "phone1": "000-5381611",
        "phone2": "000-5440625",
        "type": "private"
    },
    {
        "address": "",
        "city": "באר שבע",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "מיכאל",
        "id": 5278,
        "lastName": "אביעד",
        "paymentTerms": 0,
        "phone1": "000-3900566",
        "phone2": "000-2370432",
        "type": "private"
    },
    {
        "address": "",
        "city": "רמת גן",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "יובל",
        "id": 5277,
        "lastName": "בינה",
        "paymentTerms": 0,
        "phone1": "000-1633946",
        "phone2": "000-6561563",
        "type": "private"
    },
    {
        "address": "",
        "city": "ראש העין",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "לידור",
        "id": 5276,
        "lastName": "רינת",
        "paymentTerms": 0,
        "phone1": "000-4451404",
        "phone2": "000-5528045",
        "type": "private"
    },
    {
        "address": "",
        "city": "תל אביב",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "ארנה",
        "id": 5275,
        "lastName": "ענבר",
        "paymentTerms": 0,
        "phone1": "000-8105600",
        "phone2": "000-5137773",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "דקלה",
        "id": 5274,
        "lastName": "אוריאנה",
        "paymentTerms": 0,
        "phone1": "000-7125517",
        "phone2": "000-7689466",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "בנימין",
        "id": 5273,
        "lastName": "מתתיהו",
        "paymentTerms": 0,
        "phone1": "000-2376697",
        "phone2": "000-4432751",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירוחם",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "גפן",
        "id": 5272,
        "lastName": "רז",
        "paymentTerms": 0,
        "phone1": "000-7263455",
        "phone2": "000-5555536",
        "type": "private"
    },
    {
        "address": "",
        "city": "ראש העין",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "ארנית",
        "id": 5271,
        "lastName": "איילה",
        "paymentTerms": 0,
        "phone1": "000-6775875",
        "phone2": "000-2371985",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירושלים",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אור-פז",
        "id": 5270,
        "lastName": "חמוטל",
        "paymentTerms": 0,
        "phone1": "000-2954932",
        "phone2": "000-8919910",
        "type": "private"
    },
    {
        "address": "",
        "city": "רמת גן",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "ברעם",
        "id": 5269,
        "lastName": "אביחן",
        "paymentTerms": 0,
        "phone1": "000-7732813",
        "phone2": "000-1004383",
        "type": "private"
    },
    {
        "address": "",
        "city": "ראש העין",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "יהלי",
        "id": 5268,
        "lastName": "עבריה",
        "paymentTerms": 0,
        "phone1": "000-3454116",
        "phone2": "000-9248273",
        "type": "private"
    },
    {
        "address": "",
        "city": "תל אביב",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אור-חן",
        "id": 5267,
        "lastName": "אמתי",
        "paymentTerms": 0,
        "phone1": "000-1390102",
        "phone2": "000-5744798",
        "type": "private"
    },
    {
        "address": "",
        "city": "תל אביב",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "נחום",
        "id": 5266,
        "lastName": "אלישבע",
        "paymentTerms": 0,
        "phone1": "000-2671962",
        "phone2": "000-9204951",
        "type": "private"
    },
    {
        "address": "",
        "city": "רמת גן",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "דביר",
        "id": 5265,
        "lastName": "נעמי",
        "paymentTerms": 0,
        "phone1": "000-9242953",
        "phone2": "000-5346270",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "כרם",
        "id": 5264,
        "lastName": "יקיר",
        "paymentTerms": 0,
        "phone1": "000-7516252",
        "phone2": "000-3817755",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירושלים",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אוריאל",
        "id": 5263,
        "lastName": "עבריה",
        "paymentTerms": 0,
        "phone1": "000-1631725",
        "phone2": "000-2094961",
        "type": "private"
    },
    {
        "address": "",
        "city": "פתח תקווה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אביעם",
        "id": 5262,
        "lastName": "ורדה",
        "paymentTerms": 0,
        "phone1": "000-8040366",
        "phone2": "000-3751356",
        "type": "private"
    },
    {
        "address": "",
        "city": "תל אביב",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "אשרת",
        "id": 5261,
        "lastName": "מיכה",
        "paymentTerms": 0,
        "phone1": "000-3346434",
        "phone2": "000-6171278",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "טלמור",
        "id": 5260,
        "lastName": "שאנן",
        "paymentTerms": 0,
        "phone1": "000-9557231",
        "phone2": "000-2850806",
        "type": "private"
    },
    {
        "address": "",
        "city": "חיפה",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "מוטי",
        "id": 5259,
        "lastName": "אריה",
        "paymentTerms": 0,
        "phone1": "000-2211059",
        "phone2": "000-9186504",
        "type": "private"
    },
    {
        "address": "",
        "city": "ירושלים",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "כתר",
        "id": 5258,
        "lastName": "אילי",
        "paymentTerms": 0,
        "phone1": "000-1655622",
        "phone2": "000-2119790",
        "type": "private"
    },
    {
        "address": "",
        "city": "באר שבע",
        "customerNumber": 0,
        "discount": 0,
        "email": "test@test.com",
        "firstName": "מיטל",
        "id": 5257,
        "lastName": "רואי",
        "paymentTerms": 0,
        "phone1": "000-4486077",
        "phone2": "000-6954284",
        "type": "private"
    },
    {
        "address": "",
        "city": "טבריה",
        "customerNumber": 0,
        "discount": 1,
        "email": "test@test.com",
        "firstName": "בוני",
        "id": 5256,
        "lastName": "רבקה",
        "paymentTerms": 0,
        "phone1": "000-1247713",
        "phone2": "000-9563611",
        "type": "private"
    }
];